const fs = require('fs');
const path = require('path');

const csvChunk1 = `NO;KODE PAKET;KELAS;SEMESTER;MATA PELAJARAN;SING;MODUL;TEMA MODUL;SUB KE;KODE SUB-TUGAS;TOPIK SUB-TUGAS;STATUS;CATATAN
1;A4 - PAI - MODUL 1 - BAB 1 - 2;4;SM-I;Pendidikan Agama Islam;PAI;1;BAB 1 - 2;1;A4 - PAI - MODUL 1 - 1 - Mengkaji Q.S. Al-Hujurat/49:13;Mengkaji Q.S. Al-Hujurat/49:13;Belum Selesai;
1;A4 - PAI - MODUL 1 - BAB 1 - 2;4;SM-I;Pendidikan Agama Islam;PAI;1;BAB 1 - 2;2;A4 - PAI - MODUL 1 - 2 Teladan Mulia Asmaulhusna;Teladan Mulia Asmaulhusna;Belum Selesai;
2;A4 - PAI - MODUL 2 - BAB 3 - 4;4;SM-I;Pendidikan Agama Islam;PAI;2;BAB 3 - 4;1;A4 - PAI - MODUL 2 - 1 - Indahnya Saling Menghargai dalam Keragaman;Indahnya Saling Menghargai dalam Keragaman;Belum Selesai;
2;A4 - PAI - MODUL 2 - BAB 3 - 4;4;SM-I;Pendidikan Agama Islam;PAI;2;BAB 3 - 4;2;A4 - PAI - MODUL 2 - 2 Menyambut Usia Balig;Menyambut Usia Balig;Belum Selesai;
3;A4 - PAI - MODUL 3 - BAB 5 - 6;4;SM-I;Pendidikan Agama Islam;PAI;3;BAB 5 - 6;1;A4 - PAI - MODUL 3 - 1 - Kisah Hijrah Nabi Muhammad SAW;Kisah Hijrah Nabi Muhammad SAW;Belum Selesai;
3;A4 - PAI - MODUL 3 - BAB 5 - 6;4;SM-I;Pendidikan Agama Islam;PAI;3;BAB 5 - 6;2;A4 - PAI - MODUL 3 - 2 Mengkaji Q.S. At-Tin;Mengkaji Q.S. At-Tin;Belum Selesai;
6;A4 - BIN - MODUL 1 - Indahnya Kebersamaan;4;SM-I;Bahasa Indonesia;BIN;1;Indahnya Kebersamaan;1;A4 - BIN - MODUL 1 - 1 - KERAGAMAN BUDAYA NEGERIKU;KERAGAMAN BUDAYA NEGERIKU;Belum Selesai;
6;A4 - BIN - MODUL 1 - Indahnya Kebersamaan;4;SM-I;Bahasa Indonesia;BIN;1;Indahnya Kebersamaan;2;A4 - BIN - MODUL 1 - 2 KEBERSAMAAN DALAM KERAGAMAN;KEBERSAMAAN DALAM KERAGAMAN;Belum Selesai;
7;A4 - BIN - MODUL 2 - Profesi dan Pekerjaan di Sekitar Kita;4;SM-I;Bahasa Indonesia;BIN;2;Profesi dan Pekerjaan di Sekitar Kita;1;A4 - BIN - MODUL 2 - 1 - PROFESI DAN PEKERJAAN DI SEKITAR KITA;PROFESI DAN PEKERJAAN DI SEKITAR KITA;Belum Selesai;
7;A4 - BIN - MODUL 2 - Profesi dan Pekerjaan di Sekitar Kita;4;SM-I;Bahasa Indonesia;BIN;2;Profesi dan Pekerjaan di Sekitar Kita;2;A4 - BIN - MODUL 2 - 2 BARANG DAN JASA;BARANG DAN JASA;Belum Selesai;
7;A4 - BIN - MODUL 2 - Profesi dan Pekerjaan di Sekitar Kita;4;SM-I;Bahasa Indonesia;BIN;2;Profesi dan Pekerjaan di Sekitar Kita;3;A4 - BIN - MODUL 2 - 3 KENYAMANAN KERJA;KENYAMANAN KERJA;Belum Selesai;
8;A4 - BIN - MODUL 3 - Peralatan Rumah Tangga;4;SM-I;Bahasa Indonesia;BIN;3;Peralatan Rumah Tangga;1;A4 - BIN - MODUL 3 - 1 - MENGGUNAKAN PERALATAN RUMAH TANGGA;MENGGUNAKAN PERALATAN RUMAH TANGGA;Belum Selesai;
8;A4 - BIN - MODUL 3 - Peralatan Rumah Tangga;4;SM-I;Bahasa Indonesia;BIN;3;Peralatan Rumah Tangga;2;A4 - BIN - MODUL 3 - 2 PERAWATAN PERALATAN RUMAH TANGGA;PERAWATAN PERALATAN RUMAH TANGGA;Belum Selesai;
11;A4 - IPA - MODUL 1 - Makhluk Hidup di Sekitar Kita;4;SM-I;Ilmu Pengetahuan Alam;IPA;1;Makhluk Hidup di Sekitar Kita;1;A4 - IPA - MODUL 1 - 1 - TUMBUHAN DI SEKITAR KITA;TUMBUHAN DI SEKITAR KITA;Belum Selesai;
11;A4 - IPA - MODUL 1 - Makhluk Hidup di Sekitar Kita;4;SM-I;Ilmu Pengetahuan Alam;IPA;1;Makhluk Hidup di Sekitar Kita;2;A4 - IPA - MODUL 1 - 2 HEWAN DI SEKITAR KITA;HEWAN DI SEKITAR KITA;Belum Selesai;
12;A4 - IPA - MODUL 2 - Siklus Hidup dan Pelestarian;4;SM-I;Ilmu Pengetahuan Alam;IPA;2;Siklus Hidup dan Pelestarian;1;A4 - IPA - MODUL 2 - 1 - BAGAIMANA SIKLUS HIDUP HEWAN ITU ?;BAGAIMANA SIKLUS HIDUP HEWAN ITU ?;Belum Selesai;
12;A4 - IPA - MODUL 2 - Siklus Hidup dan Pelestarian;4;SM-I;Ilmu Pengetahuan Alam;IPA;2;Siklus Hidup dan Pelestarian;2;A4 - IPA - MODUL 2 - 2 BAGAIMANA UPAYA PELESTARIAN HEWAN DAN TUMBUHAN ?;BAGAIMANA UPAYA PELESTARIAN HEWAN DAN TUMBUHAN ?;Belum Selesai;
13;A4 - IPA - MODUL 3 - Indahnya Negeriku;4;SM-I;Ilmu Pengetahuan Alam;IPA;3;Indahnya Negeriku;1;A4 - IPA - MODUL 3 - 1 - BERAGAMNYA SUMBER DAYA ALAM NEGERIKU;BERAGAMNYA SUMBER DAYA ALAM NEGERIKU;Belum Selesai;
13;A4 - IPA - MODUL 3 - Indahnya Negeriku;4;SM-I;Ilmu Pengetahuan Alam;IPA;3;Indahnya Negeriku;2;A4 - IPA - MODUL 3 - 2 YUK KITA JAGA KELESTARIAN ALAM INDONESIA;YUK KITA JAGA KELESTARIAN ALAM INDONESIA;Belum Selesai;
16;A4 - IPS - MODUL 1 - Tak Kenal Maka Tak Sayang;4;SM-I;Ilmu Pengetahuan Sosial;IPS;1;Tak Kenal Maka Tak Sayang;1;A4 - IPS - MODUL 1 - 1 - SAYANGI ALAM INDONESIA;SAYANGI ALAM INDONESIA;Belum Selesai;
16;A4 - IPS - MODUL 1 - Tak Kenal Maka Tak Sayang;4;SM-I;Ilmu Pengetahuan Sosial;IPS;1;Tak Kenal Maka Tak Sayang;2;A4 - IPS - MODUL 1 - 2 FLORA DAN FAUNA INDONESIA;FLORA DAN FAUNA INDONESIA;Belum Selesai;
17;A4 - IPS - MODUL 2 - Mendunia karena potensi Lokal;4;SM-I;Ilmu Pengetahuan Sosial;IPS;2;Mendunia karena potensi Lokal;1;A4 - IPS - MODUL 2 - 1 - PENDUDUK INDONESIA;PENDUDUK INDONESIA;Belum Selesai;
17;A4 - IPS - MODUL 2 - Mendunia karena potensi Lokal;4;SM-I;Ilmu Pengetahuan Sosial;IPS;2;Mendunia karena potensi Lokal;2;A4 - IPS - MODUL 2 - 2 PENTINGNYA PEMANFAATAN SUMBER DAYA ALAM;PENTINGNYA PEMANFAATAN SUMBER DAYA ALAM;Belum Selesai;
18;A4 - IPS - MODUL 3 - Karya Untuk Merah Putih;4;SM-I;Ilmu Pengetahuan Sosial;IPS;3;Karya Untuk Merah Putih;1;A4 - IPS - MODUL 3 - 1 - MENCARI MUTIARA YANG TERPENDAM;MENCARI MUTIARA YANG TERPENDAM;Belum Selesai;
18;A4 - IPS - MODUL 3 - Karya Untuk Merah Putih;4;SM-I;Ilmu Pengetahuan Sosial;IPS;3;Karya Untuk Merah Putih;2;A4 - IPS - MODUL 3 - 2 DEMI MERAH PUTIH BERKIBAR;DEMI MERAH PUTIH BERKIBAR;Belum Selesai;
18;A4 - IPS - MODUL 3 - Karya Untuk Merah Putih;4;SM-I;Ilmu Pengetahuan Sosial;IPS;3;Karya Untuk Merah Putih;3;A4 - IPS - MODUL 3 - 3 BERKARYA DI RUMAH BERSAMA;BERKARYA DI RUMAH BERSAMA;Belum Selesai;
21;A4 - MTK - MODUL 1 - Indahnya Berbagi;4;SM-I;Matematika;MTK;1;Indahnya Berbagi;1;A4 - MTK - MODUL 1 - 1 - MENGENAL PECAHAN;MENGENAL PECAHAN;Belum Selesai;
21;A4 - MTK - MODUL 1 - Indahnya Berbagi;4;SM-I;Matematika;MTK;1;Indahnya Berbagi;2;A4 - MTK - MODUL 1 - 2 PECAHAN SENILAI;PECAHAN SENILAI;Belum Selesai;
21;A4 - MTK - MODUL 1 - Indahnya Berbagi;4;SM-I;Matematika;MTK;1;Indahnya Berbagi;3;A4 - MTK - MODUL 1 - 3 MEMBANDINGKAN PECAHAN;MEMBANDINGKAN PECAHAN;Belum Selesai;
21;A4 - MTK - MODUL 1 - Indahnya Berbagi;4;SM-I;Matematika;MTK;1;Indahnya Berbagi;4;A4 - MTK - MODUL 1 - 4 PECAHAN BIASA, PERSEN DAN DESIMAL;PECAHAN BIASA, PERSEN DAN DESIMAL;Belum Selesai;
21;A4 - MTK - MODUL 1 - Indahnya Berbagi;4;SM-I;Matematika;MTK;1;Indahnya Berbagi;5;A4 - MTK - MODUL 1 - 5 PENJUMLAHAN DAN PENGURANGAN PECAHAN;PENJUMLAHAN DAN PENGURANGAN PECAHAN;Belum Selesai;
21;A4 - MTK - MODUL 1 - Indahnya Berbagi;4;SM-I;Matematika;MTK;1;Indahnya Berbagi;6;A4 - MTK - MODUL 1 - 6 PENJUMLAHAN DAN PENGURANGAN PECAHAN DESIMAL DAN PERSEN;PENJUMLAHAN DAN PENGURANGAN PECAHAN DESIMAL DAN PERSEN;Belum Selesai;
21;A4 - MTK - MODUL 1 - Indahnya Berbagi;4;SM-I;Matematika;MTK;1;Indahnya Berbagi;7;A4 - MTK - MODUL 1 - 7 PEMBULATAN PECAHAN;PEMBULATAN PECAHAN;Belum Selesai;
22;A4 - MTK - MODUL 2 - Sehat Berolahraga;4;SM-I;Matematika;MTK;2;Sehat Berolahraga;1;A4 - MTK - MODUL 2 - 1 - KELIPATAN, FAKTOR DAN BILANGAN PRIMA;KELIPATAN, FAKTOR DAN BILANGAN PRIMA;Belum Selesai;
22;A4 - MTK - MODUL 2 - Sehat Berolahraga;4;SM-I;Matematika;MTK;2;Sehat Berolahraga;2;A4 - MTK - MODUL 2 - 2 KELIPATAN PERSEKUTUAN, KPK, FAKTOR PERSEKUTUAN DAN FPB;KELIPATAN PERSEKUTUAN, KPK, FAKTOR PERSEKUTUAN DAN FPB;Belum Selesai;
23;A4 - MTK - MODUL 3 - Ragam Budaya;4;SM-I;Matematika;MTK;3;Ragam Budaya;1;A4 - MTK - MODUL 3 - 1 - BANGUNAN ADAT;BANGUNAN ADAT;Belum Selesai;
23;A4 - MTK - MODUL 3 - Ragam Budaya;4;SM-I;Matematika;MTK;3;Ragam Budaya;2;A4 - MTK - MODUL 3 - 2 BUDAYA DAERAH;BUDAYA DAERAH;Belum Selesai;
26;A4 - PPKn - MODUL 1 - Garuda di Dadaku;4;SM-I;PPKn;PPKn;1;Garuda di Dadaku;1;A4 - PPKn - MODUL 1 - 1 - KENALI AKU : PANCASILA;KENALI AKU : PANCASILA;Belum Selesai;
26;A4 - PPKn - MODUL 1 - Garuda di Dadaku;4;SM-I;PPKn;PPKn;1;Garuda di Dadaku;2;A4 - PPKn - MODUL 1 - 2 PANCASILA: BULAT DAN UTUH;PANCASILA: BULAT DAN UTUH;Belum Selesai;
26;A4 - PPKn - MODUL 1 - Garuda di Dadaku;4;SM-I;PPKn;PPKn;1;Garuda di Dadaku;3;A4 - PPKn - MODUL 1 - 3 PANCASILA DALAM AKTIVITAS KESEHARIAN;PANCASILA DALAM AKTIVITAS KESEHARIAN;Belum Selesai;
27;A4 - PPKn - MODUL 2 - Harmoni dalam Kehidupan;4;SM-I;PPKn;PPKn;2;Harmoni dalam Kehidupan;1;A4 - PPKn - MODUL 2 - 1 - MENDAHULUKAN KEWAJIBAN;MENDAHULUKAN KEWAJIBAN;Belum Selesai;
27;A4 - PPKn - MODUL 2 - Harmoni dalam Kehidupan;4;SM-I;PPKn;PPKn;2;Harmoni dalam Kehidupan;2;A4 - PPKn - MODUL 2 - 2 MENERIMA HAKKU;MENERIMA HAKKU;Belum Selesai;
`;

fs.writeFileSync(path.join(__dirname, 'raw_part1.csv'), csvChunk1.trim() + '\n');
console.log('Part 1 saved');
